export const ACTIVITY_MODES = {
   'WITH_YOU': 'WITH_YOU',
   'CAFE': 'CAFE',
   'QUEUE': 'QUEUE',
   'STORE': 'STORE'
};

export const ACTIVITY_SUB_MODE_LINKER = {
   'CAFE': ['SELF-SERVICE', 'WAITER-SERVICE'],
   'STORE': ['LARGE', 'MEDIUM', 'SMALL'],
 };

export const ACTIVITY_STATUS = {
    'QUEUE':'QUEUE',
    'PAYMENT_CALL':'PAYMENT_CALL',
    'WAIT_ITEM':'WAIT_ITEM',
    'WAIT_OP':'WAIT_OP',
    'DEFAULT': 'DEFAULT',
    'CLEAR_TABLE': 'CLEAR_TABLE',
    'STAND_CLOSE': 'STAND_CLOSE',
};

export const COMPANION_MODE_STATUS_LINKER = {
   'WITH_YOU': ['DEFAULT', 'QUEUE', 'WAIT_OP' ],
   'CAFE': ['QUEUE','PAYMENT_CALL','WAIT_ITEM','WAIT_OP','CLEAR_TABLE','STAND_CLOSE'],
   'QUEUE': ['QUEUE'],
   'STORE': ['QUEUE','PAYMENT_CALL','WAIT_ITEM','WAIT_OP'],
   'WITH_CLIENT': ['DEFAULT'],
}

export const STATUS_BUTTON_LABELS = {
    [ACTIVITY_STATUS.QUEUE]: 'Queue',
    [ACTIVITY_STATUS.PAYMENT_CALL]: 'Payment',
    [ACTIVITY_STATUS.WAIT_ITEM]: 'waiting for item',
    [ACTIVITY_STATUS.WAIT_OP]: 'waiting OP',
    [ACTIVITY_STATUS.DEFAULT]: 'Default',   
    [ACTIVITY_STATUS.CLEAR_TABLE]: 'Clear Table',
    [ACTIVITY_STATUS.STAND_CLOSE]: 'Stand Close',
};

export const CLIENT_SEND_MSG = {
    'STOP_ACTIVITY':'STOP_ACTIVITY',
    'COMPLETE_MODE_CAFE':'COMPLETE_MODE_CAFE',
};

export const COMPANION_ROLES = {
    'PRIMARY': 'PRIMARY',
    'SECONDARY': 'SECONDARY',
};

export const MESSAGE_TYPES_TO_COMPANION = {
    'STOP_ACTIVITY': 'STOP_ACTIVITY',
    'MODE_END': 'MODE_END',
    'STAND_GUARD': 'WAIT_OP',
}

export const MSG_STATUS = {
    'UNREAD': 'UNREAD',
    'OPENED': 'OPENED',
    'ACTIONED': 'ACTIONED'
};

export const MODE_DEFAULT_STATUS: Record<string, string> = {
  [ACTIVITY_MODES.CAFE]: ACTIVITY_STATUS.WAIT_OP,
  [ACTIVITY_MODES.STORE]: ACTIVITY_STATUS.WAIT_OP,
  [ACTIVITY_MODES.WITH_YOU]: ACTIVITY_STATUS.DEFAULT,
};

export const CLIENT_INSTRUCTION_MANUAL = {
    'WITH_YOU': {
        'DEFAULT': 'DEFAULT',
        'QUEUE': 'QUEUE',
        'WAIT_OP': 'WAIT_OP',
    },
    'CAFE': {
        'WAIT_OP': 'WAIT_OP',
        'BRING_STAFF': 'BRING_STAFF',
        'STAND_CLOSE': 'STAND_CLOSE',
        'ORDER_CALL': 'ORDER_CALL',
        'I_AM_DONE': 'I_AM_DONE',
    },
    'STORE': {
        'I_AM_DONE': 'I_AM_DONE',
        'CLOSE_ASSIST': 'CLOSE_ASSIST',
        'BRING_STAFF': 'BRING_STAFF',
        'WAIT_OP': 'WAIT_OP',
    },
}

export const CLIENT_INSTRUCTION_OPTIONS = {
    DEFAULT: [],
    QUEUE: ['CANCEL'],
    WAIT_OP: ['CANCEL'],
    CLEAR_TABLE: ['CANCEL'],
    STAND_CLOSE: ['CANCEL'],
    ORDER_CALL: ['CANCEL'],
    PAYMENT_CALL: [],
    WAIT_ITEM: [],
}   